version: "3.8"

services:
  developersden.reverseproxy:
    build: 
      context: ./nginx
      dockerfile: Dockerfile
    expose:
      - "80:80"
      - "443:443"
    restart: always
  developersden.database:
    container_name: developersden.database
    image: postgres
    restart: unless-stopped
    env_file:
      - database.env
    ports:
      - "5439:5432"
  developersden.api:
    image: ${DOCKER_REGISTRY-}developersden.api
    container_name: developersden.api
    restart: unless-stopped
    build:
      context: ../DevelopersDen
      dockerfile: ./DevelopersDen.API/Dockerfile
    expose:
      - "80"
    depends_on:
      - developersden.database
  developersden.web:
    container_name: developersden.web
    restart: unless-stopped
    build:
     context: ./DevelopersDen.Client
     dockerfile: ./Dockerfile
    expose:
      - '80'
    depends_on:
      - developersden.api
  developersden.nginx:
    image: nginx:latest
    container_name: developersden.nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./certs/fullchain.pem:/etc/ssl/certs/fullchain.pem
      - ./certs/privkey.pem:/etc/ssl/private/privkey.pem
    depends_on:
      - developersden.api
      - developersden.web