version: "3.8"

services:
  developersden.database:
    container_name: developersden.database
    image: postgres
    restart: unless-stopped
    env_file:
      - database.env
    ports:
      - "5439:5432"
  developersden.api:
    image: ${DOCKER_REGISTRY-}developersden.api
    container_name: developersden.api
    restart: unless-stopped
    build:
      context: ../DevelopersDen
      dockerfile: /DevelopersDen.API/Dockerfile
    ports:
      - "8080:8080"
      - "8081:8081"
    depends_on:
      - developersden.database
  developersden.web:
    container_name: developersden.web
    restart: unless-stopped
    build:
     context: ./DevelopersDen.Client
     dockerfile: ./Dockerfile
    ports:
      - '8082:80'
      - '8084:443'
    depends_on:
      - developersden.api